# Change baseurl before deploy
baseurl = "https://liguobao.github.io"
[pagination]
  pagerSize = 10
title = "李国宝"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
languageCode = "zh-cn"

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "liguobao-blog"
